# docker-compose.yml

version: '3.8'
services:
  test-db:
    image: postgres:13.5
    ports:
      - '5435:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: test_nest
    networks:
    - pgnet
  dev-db:
    image: postgres:13.5
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: nest
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - pgnet
networks:
  pgnet:
volumes:
  postgres:
